/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      order: 1000,
      icon: 'material-symbols:help-outline-rounded'
    }
  },
  {
    name: 'function',
    path: '/function',
    component: 'layout.base',
    meta: {
      title: 'function',
      i18nKey: 'route.function',
      icon: 'icon-park-outline:all-application',
      order: 6,
      hideInMenu: true
    },
    children: [
      {
        name: 'function_hide-child',
        path: '/function/hide-child',
        meta: {
          title: 'function_hide-child',
          i18nKey: 'route.function_hide-child',
          icon: 'material-symbols:filter-list-off',
          order: 2
        },
        redirect: '/function/hide-child/one',
        children: [
          {
            name: 'function_hide-child_one',
            path: '/function/hide-child/one',
            component: 'view.function_hide-child_one',
            meta: {
              title: 'function_hide-child_one',
              i18nKey: 'route.function_hide-child_one',
              icon: 'material-symbols:filter-list-off',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          },
          {
            name: 'function_hide-child_three',
            path: '/function/hide-child/three',
            component: 'view.function_hide-child_three',
            meta: {
              title: 'function_hide-child_three',
              i18nKey: 'route.function_hide-child_three',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          },
          {
            name: 'function_hide-child_two',
            path: '/function/hide-child/two',
            component: 'view.function_hide-child_two',
            meta: {
              title: 'function_hide-child_two',
              i18nKey: 'route.function_hide-child_two',
              hideInMenu: true,
              activeMenu: 'function_hide-child'
            }
          }
        ]
      },
      {
        name: 'function_multi-tab',
        path: '/function/multi-tab',
        component: 'view.function_multi-tab',
        meta: {
          title: 'function_multi-tab',
          i18nKey: 'route.function_multi-tab',
          icon: 'ic:round-tab',
          multiTab: true,
          hideInMenu: true,
          activeMenu: 'function_tab'
        }
      },
      {
        name: 'function_request',
        path: '/function/request',
        component: 'view.function_request',
        meta: {
          title: 'function_request',
          i18nKey: 'route.function_request',
          icon: 'carbon:network-overlay',
          order: 3
        }
      },
      {
        name: 'function_super-page',
        path: '/function/super-page',
        component: 'view.function_super-page',
        meta: {
          title: 'function_super-page',
          i18nKey: 'route.function_super-page',
          icon: 'ic:round-supervisor-account',
          order: 5,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'function_tab',
        path: '/function/tab',
        component: 'view.function_tab',
        meta: {
          title: 'function_tab',
          i18nKey: 'route.function_tab',
          icon: 'ic:round-tab',
          order: 1
        }
      },
      {
        name: 'function_toggle-auth',
        path: '/function/toggle-auth',
        component: 'view.function_toggle-auth',
        meta: {
          title: 'function_toggle-auth',
          i18nKey: 'route.function_toggle-auth',
          icon: 'ic:round-construction',
          order: 4
        }
      }
    ]
  },
  {
    name: 'group',
    path: '/group',
    component: 'layout.base$view.group',
    meta: {
      title: 'group',
      i18nKey: 'route.group',
      order: 30,
      icon: 'material-symbols:group-work-outline'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'material-symbols:dashboard-outline-rounded',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'job',
    path: '/job',
    component: 'layout.base',
    meta: {
      title: 'job',
      i18nKey: 'route.job',
      order: 50,
      icon: 'eos-icons:cronjob'
    },
    children: [
      {
        name: 'job_batch',
        path: '/job/batch',
        component: 'view.job_batch',
        meta: {
          title: 'job_batch',
          i18nKey: 'route.job_batch',
          icon: 'carbon:batch-job',
          order: 20
        }
      },
      {
        name: 'job_task',
        path: '/job/task',
        component: 'view.job_task',
        meta: {
          title: 'job_task',
          i18nKey: 'route.job_task',
          icon: 'octicon:tasklist',
          order: 10
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 9,
      roles: ['R_ADMIN'],
      hideInMenu: true
    },
    children: [
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          order: 3,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          order: 2,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 1,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          roles: ['R_ADMIN'],
          activeMenu: 'manage_user'
        }
      }
    ]
  },
  {
    name: 'multi-menu',
    path: '/multi-menu',
    component: 'layout.base',
    meta: {
      title: 'multi-menu',
      i18nKey: 'route.multi-menu',
      order: 8,
      hideInMenu: true
    },
    children: [
      {
        name: 'multi-menu_first',
        path: '/multi-menu/first',
        meta: {
          title: 'multi-menu_first',
          i18nKey: 'route.multi-menu_first',
          order: 1
        },
        children: [
          {
            name: 'multi-menu_first_child',
            path: '/multi-menu/first/child',
            component: 'view.multi-menu_first_child',
            meta: {
              title: 'multi-menu_first_child',
              i18nKey: 'route.multi-menu_first_child'
            }
          }
        ]
      },
      {
        name: 'multi-menu_second',
        path: '/multi-menu/second',
        meta: {
          title: 'multi-menu_second',
          i18nKey: 'route.multi-menu_second',
          order: 2
        },
        children: [
          {
            name: 'multi-menu_second_child',
            path: '/multi-menu/second/child',
            meta: {
              title: 'multi-menu_second_child',
              i18nKey: 'route.multi-menu_second_child'
            },
            children: [
              {
                name: 'multi-menu_second_child_home',
                path: '/multi-menu/second/child/home',
                component: 'view.multi-menu_second_child_home',
                meta: {
                  title: 'multi-menu_second_child_home',
                  i18nKey: 'route.multi-menu_second_child_home'
                }
              }
            ]
          }
        ]
      }
    ]
  },
  {
    name: 'namespace',
    path: '/namespace',
    component: 'layout.base$view.namespace',
    meta: {
      title: 'namespace',
      i18nKey: 'route.namespace',
      icon: 'eos-icons:namespace',
      order: 20,
      roles: ['R_ADMIN']
    }
  },
  {
    name: 'notify',
    path: '/notify',
    component: 'layout.base',
    meta: {
      title: 'notify',
      i18nKey: 'route.notify',
      order: 100,
      icon: 'material-symbols:notifications-active-outline-rounded'
    },
    children: [
      {
        name: 'notify_recipient',
        path: '/notify/recipient',
        component: 'view.notify_recipient',
        meta: {
          title: 'notify_recipient',
          i18nKey: 'route.notify_recipient',
          icon: 'fluent:people-call-20-filled'
        }
      },
      {
        name: 'notify_scene',
        path: '/notify/scene',
        component: 'view.notify_scene',
        meta: {
          title: 'notify_scene',
          i18nKey: 'route.notify_scene',
          icon: 'cbi:scene-dynamic'
        }
      }
    ]
  },
  {
    name: 'pods',
    path: '/pods',
    component: 'layout.base$view.pods',
    meta: {
      title: 'pods',
      i18nKey: 'route.pods',
      icon: 'ant-design:database-outlined',
      order: 10
    }
  },
  {
    name: 'retry',
    path: '/retry',
    component: 'layout.base',
    meta: {
      title: 'retry',
      i18nKey: 'route.retry',
      order: 70,
      icon: 'carbon:retry-failed'
    },
    children: [
      {
        name: 'retry_dead-letter',
        path: '/retry/dead-letter',
        component: 'view.retry_dead-letter',
        meta: {
          title: 'retry_dead-letter',
          i18nKey: 'route.retry_dead-letter',
          icon: 'streamline:interface-arrows-synchronize-warning-arrow-fail-notification-sync-warning-failure-synchronize-error',
          order: 30
        }
      },
      {
        name: 'retry_log',
        path: '/retry/log',
        component: 'view.retry_log',
        meta: {
          title: 'retry_log',
          i18nKey: 'route.retry_log',
          icon: 'tabler:logs',
          order: 20
        }
      },
      {
        name: 'retry_scene',
        path: '/retry/scene',
        component: 'view.retry_scene',
        meta: {
          title: 'retry_scene',
          i18nKey: 'route.retry_scene',
          icon: 'cbi:scene-dynamic',
          order: 1
        }
      },
      {
        name: 'retry_task',
        path: '/retry/task',
        component: 'view.retry_task',
        meta: {
          title: 'retry_task',
          i18nKey: 'route.retry_task',
          icon: 'octicon:tasklist',
          order: 10
        }
      }
    ]
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base',
    meta: {
      title: 'user',
      i18nKey: 'route.user',
      order: 900,
      icon: 'material-symbols:manage-accounts',
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'user_manager',
        path: '/user/manager',
        component: 'view.user_manager',
        meta: {
          title: 'user_manager',
          i18nKey: 'route.user_manager',
          icon: 'streamline:interface-user-multiple-close-geometric-human-multiple-person-up-user',
          order: 900,
          roles: ['R_ADMIN']
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  },
  {
    name: 'workflow',
    path: '/workflow',
    component: 'layout.base',
    meta: {
      title: 'workflow',
      i18nKey: 'route.workflow',
      order: 60,
      icon: 'lucide:workflow'
    },
    children: [
      {
        name: 'workflow_batch',
        path: '/workflow/batch',
        component: 'view.workflow_batch',
        meta: {
          title: 'workflow_batch',
          i18nKey: 'route.workflow_batch',
          icon: 'carbon:batch-job',
          order: 10
        }
      },
      {
        name: 'workflow_form',
        path: '/workflow/form',
        meta: {
          title: 'workflow_form',
          hideInMenu: true,
          i18nKey: 'route.workflow_form'
        },
        children: [
          {
            name: 'workflow_form_add',
            path: '/workflow/form/add',
            component: 'view.workflow_form_add',
            meta: {
              hideInMenu: true,
              title: 'workflow_form_add',
              i18nKey: 'route.workflow_form_add'
            }
          },
          {
            name: 'workflow_form_batch',
            path: '/workflow/form/batch',
            component: 'view.workflow_form_batch',
            meta: {
              hideInMenu: true,
              title: 'workflow_form_batch',
              i18nKey: 'route.workflow_form_batch'
            }
          },
          {
            name: 'workflow_form_copy',
            path: '/workflow/form/copy',
            component: 'view.workflow_form_copy',
            meta: {
              title: 'workflow_form_copy',
              hideInMenu: true,
              i18nKey: 'route.workflow_form_copy'
            }
          },
          {
            name: 'workflow_form_detail',
            path: '/workflow/form/detail',
            component: 'view.workflow_form_detail',
            meta: {
              title: 'workflow_form_detail',
              hideInMenu: true,
              i18nKey: 'route.workflow_form_detail'
            }
          },
          {
            name: 'workflow_form_edit',
            path: '/workflow/form/edit',
            component: 'view.workflow_form_edit',
            meta: {
              title: 'workflow_form_edit',
              hideInMenu: true,
              i18nKey: 'route.workflow_form_edit'
            }
          }
        ]
      },
      {
        name: 'workflow_task',
        path: '/workflow/task',
        component: 'view.workflow_task',
        meta: {
          title: 'workflow_task',
          i18nKey: 'route.workflow_task',
          icon: 'octicon:tasklist',
          order: 1
        }
      }
    ]
  }
];
